### ISSUE TITLE
Exception in Jetbrains 2023.2 EAP IDEs

### ISSUE THREAD

**Issue by yohannlog** [codota/tabnine-intellij#553]
Hi!

I've got an exception when using tabnine in EAP version (When autocompleting with tab key).
This causes an exception causing the inability to copy paste and this causes several bugs on undo action.

This is the error:
java.lang.Throwable: Assertion failed: Undoable actions allowed inside commands only (see com.intellij.openapi.command.CommandProcessor.executeCommand())

I had opened a bug report on Jetbrains youtrack but after investigation, it seems that the problem came from here. Here is the link: https://youtrack.jetbrains.com/issue/IDEA-323867/Undo-problem-Undoable-actions-allowed-inside-commands-only

Thanks !

gz#24636<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24636'>Zendesk ticket #24636</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @yohannlog 
Try using Tabnine on a non-EAP version.

**Comment by jingxinli33** [comment]
> Hi @yohannlog Try using Tabnine on a non-EAP version.

Hi @TzufTabnine I am also an IntelliJ IDEA plugin developer and I have encountered a similar issue as yours. The problem seems to be triggered by the auto-import command when accepting the completion suggestions. When the user attempts to undo the action using ctrl+z, this exception is thrown. Additionally, it appears that this issue only occurs in the 2023.2 EAP of the IDEA. Could you please kindly share how you managed to resolve this issue? Thanks

**Comment by yonip23** [comment]
Hi @jingxinli33 
Thanks for reporting the EAP issue, we will add this to our backlog and prioritize.

> Could you please kindly share how you managed to resolve this issue?

Are you asking how did we manage to resolve the issue on the stable versions, or the EAP version?

**Comment by Metachemix1** [comment]
@TzufTabnine this issue still occurs on Build #WS-232.8660.143, built on July 21, 2023 NON-EAP build of Webstorm, as a workaround i've temporary disabled the plugin. As it influences my workflow too much by disabling the undo /copy-paste within webstorm IDE.

Please consider re-opening this ticket.

**Comment by gvko** [comment]
Yesterday I upgraded to the latest WebStorm version `WS-232.8660.143, built on July 21, 2023` and I'm having the same issue. 
This is not resolved and the ticket should be re-opened.

**Comment by yairco1990** [comment]
We have identified an issue with the auto-import module in our plugin, which appears to conflict with the latest version of Jetbrains. We're working diligently to address this. 
In the meantime, we recommend a temporary workaround: disabling the auto-import functionality. You can do this through the TabNine settings panel in your IDE. We'll keep you updated as we work towards a resolution.

**Comment by yairco1990** [comment]
We have identified an issue with the auto-import module in our plugin, which appears to conflict with the latest version of Jetbrains. We're working diligently to address this. 
In the meantime, we recommend a temporary workaround: disabling the auto-import functionality. You can do this through the TabNine settings panel in your IDE. We'll keep you updated as we work towards a resolution.

**Comment by mkalus** [comment]
> We have identified an issue with the auto-import module in our plugin, which appears to conflict with the latest version of Jetbrains. We're working diligently to address this. In the meantime, we recommend a temporary workaround: disabling the auto-import functionality. You can do this through the TabNine settings panel in your IDE. We'll keep you updated as we work towards a resolution.

This did not solve the error for me (Ubuntu 22.04, Jetbrain IDEs installed via Toolbox). Affects all IDEs!

**Comment by TzufTabnine** [comment]
Make sure you have the latest version of Tabnine (1.0.37). It should solve the issue.

**Comment by mkalus** [comment]
Nope, it did not - I did test with the latest issue and it still throws the same error.
